
#- hosts: server_b
#  become: true
#  tasks:
#Опционально, если хотим ставим доп приложения через анзибль
#Grafana

#    - name: Copy file with owner and permissions
#      copy: src={{ item.src }} dest={{ item.dest }}
#      with_items:
#         - { src: 'grafana-enterprise_9.2.1_amd64.deb', dest: '/' }

#    - name: cp deb package
#      ansible.builtin.apt:
#        deb: grafana-enterprise_9.2.1_amd64.deb

#    - ansible.builtin.systemd:
#        state: started
#        name: grafana-server.service

# Prometheus
#    - name: Install required system packages
#      apt:
#        pkg:
#          - prometheus

#    - ansible.builtin.systemd:
#        state: started
#        name: prometheus.service